//
//  FavouriteRouter.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 24.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavouriteRoutingLogic {
    func routeToDetailCoinViewController(segue: UIStoryboardSegue?)
}

protocol FavouriteDataPassing {
    var dataStore: FavouriteDataStore? { get }
}

class FavouriteRouter: NSObject, FavouriteRoutingLogic, FavouriteDataPassing {
    
    weak var viewController: FavouriteViewController?
    var dataStore: FavouriteDataStore?
    
    // MARK: Routing
    func routeToDetailCoinViewController(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! DetailCoinViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailCoinViewControllerID") as! DetailCoinViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    func navigateToSomewhere(source: FavouriteViewController, destination: DetailCoinViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToSomewhere(source: FavouriteDataStore, destination: inout DetailCoinDataStore) {
        guard let indexPath = viewController?.tableView.indexPathForSelectedRow else { return }
        if source.isSearching {
            destination.coin = source.favouritSearshedCoins[indexPath.row]
        } else {
            destination.coin = source.favouritCoins[indexPath.row]
        }
    }
}
