//
//  DetailCoinWorker.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 23.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailCoinWorker {
    func getFavoritStatus(coinName: String) -> Bool {
        return DataManager.shared.getFavoriteStatus(for: coinName)
    }
    
    func setFavoritStatus(coinName: String, isFavorit: Bool) {
        DataManager.shared.setFavoriteStatus(for: coinName, with: isFavorit)
    }
}
