//
//  DetailCoinInteractor.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 23.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailCoinBusinessLogic {
    func doProvideCoinDetails(request: DetailCoin.ShowDetails.Request)
    func changeFavoritStatus()
}

protocol DetailCoinDataStore {
    var coin: Coin? { get set }
}

class DetailCoinInteractor: DetailCoinBusinessLogic, DetailCoinDataStore {
    var presenter: DetailCoinPresentationLogic?
    var worker: DetailCoinWorker = DetailCoinWorker()
    var coin: Coin?
    var isFavorit: Bool = false

    
    // MARK: Provide Coin Details
    func doProvideCoinDetails(request: DetailCoin.ShowDetails.Request) {
        guard let coin = coin else { return }
        isFavorit = worker.getFavoritStatus(coinName: coin.name)
        
        let response = DetailCoin.ShowDetails.Response(coinName: coin.name ,
                                                       coinPrice: coin.current_price,
                                                       marketCap: coin.market_cap,
                                                       curculatingSupply: coin.circulating_supply,
                                                       maxSupply: coin.max_supply,
                                                       high24h: coin.high_24h,
                                                       low24h: coin.low_24h,
                                                       priceChange24h: coin.price_change_24h,
                                                       favoritStatus: isFavorit)
        presenter?.presentCoinDetails(response: response)
    }
    
    //MARK: Change favorit status
    func changeFavoritStatus() {
        guard let coin = coin else { return }
        isFavorit.toggle()
        worker.setFavoritStatus(coinName: coin.name, isFavorit: isFavorit)
        presenter?.presentFavoritStatus(response: DetailCoin.SetFavoritStatus.Response(favoritStatus: isFavorit))
    }
}
