//
//  MainRouter.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 24.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToDetailCoinViewController(segue: UIStoryboardSegue?)
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?

    
    // MARK: Routing
    
    func routeToDetailCoinViewController(segue: UIStoryboardSegue?) {
      if let segue = segue {
        let destinationVC = segue.destination as! DetailCoinViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetailCoinViewController(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailCoinViewControllerID") as! DetailCoinViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetailCoinViewController(source: dataStore!, destination: &destinationDS)
        navigateToDetailCoinViewController(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateToDetailCoinViewController(source: MainViewController, destination: DetailCoinViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetailCoinViewController(source: MainDataStore, destination: inout DetailCoinDataStore) {
        guard let indexPath = viewController?.tableView.indexPathForSelectedRow else { return }
        destination.coin = source.coins[indexPath.row]
    }
}
