//
//  MainInteractor.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 24.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func fetchListCoins()
}

protocol MainDataStore {
    var coins: [Coin] { get }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    
    var presenter: MainPresentationLogic?
    var coins: [Coin] = []
    
    // MARK: Do something
    
    func fetchListCoins() {
        coins.removeAll()
        NetworkManager.shared.fetchData { [unowned self] coin in
            coins = coin
            let response = Main.ShowCoinsList.Response(coins: coins)
            presenter?.presentListCoins(response: response)
        }
    }
}
