//
//  MainPresenter.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 24.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentListCoins(response: Main.ShowCoinsList.Response)
}

class MainPresenter: MainPresentationLogic {
    
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentListCoins(response: Main.ShowCoinsList.Response) {
        var viewModeForCell: [Main.ShowCoinsList.ViewModel.CoinCellViewModel] = []
        response.coins.forEach { coin in
            viewModeForCell.append(Main.ShowCoinsList.ViewModel.CoinCellViewModel(imageCoin: coin.image,
                                                                              nameCoin: coin.name,
                                                                              priceChangePercentage24h: coin.price_change_percentage_24h,
                                                                              priceCoin: coin.current_price))
        }
        let viewModel = Main.ShowCoinsList.ViewModel(coinCellViewModel: viewModeForCell)
        viewController?.displayCoins(viewModel: viewModel)
    }
}
