//
//  CryptoTableViewCellWorker.swift
//  CryptoTrackerV2
//
//  Created by Алексей Однолько on 23.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CryptoTableViewCellWorker {
    func fetchImageData(imageUrl: URL) -> Data? {
        return ImageManager.shared.fetchImageData(from: imageUrl)
    }
}
